# CMake generated Testfile for 
# Source directory: /home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom
# Build directory: /home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(boot "./bin/boot")
set_tests_properties(boot PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;44;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(boot_ROM "./bin/boot" "--" "--rom")
set_tests_properties(boot_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;45;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_hw "./bin/init_hw")
set_tests_properties(init_hw PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;47;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_hw_ROM "./bin/init_hw" "--" "--rom")
set_tests_properties(init_hw_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;47;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(reset_via "./bin/reset_via")
set_tests_properties(reset_via PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;48;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(reset_via_ROM "./bin/reset_via" "--" "--rom")
set_tests_properties(reset_via_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;48;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(get_hw_info "./bin/get_hw_info")
set_tests_properties(get_hw_info PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;32;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;49;UT2;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(get_hw_info_ROM "./bin/get_hw_info" "--" "--rom")
set_tests_properties(get_hw_info_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;36;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;49;UT2;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_mb "./bin/check_mb")
set_tests_properties(check_mb PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;32;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;50;UT2;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_mb_ROM "./bin/check_mb" "--" "--rom")
set_tests_properties(check_mb_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;36;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;50;UT2;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_mmu "./bin/init_mmu")
set_tests_properties(init_mmu PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;51;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_mmu_ROM "./bin/init_mmu" "--" "--rom")
set_tests_properties(init_mmu_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;51;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_fpu "./bin/has_fpu")
set_tests_properties(has_fpu PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;52;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_fpu_ROM "./bin/has_fpu" "--" "--rom")
set_tests_properties(has_fpu_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;52;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_iifx_exp1 "./bin/test_iifx_exp1")
set_tests_properties(test_iifx_exp1 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;53;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_iifx_exp1_ROM "./bin/test_iifx_exp1" "--" "--rom")
set_tests_properties(test_iifx_exp1_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;53;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_via "./bin/has_via")
set_tests_properties(has_via PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;54;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_via_ROM "./bin/has_via" "--" "--rom")
set_tests_properties(has_via_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;54;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_rbv "./bin/has_rbv")
set_tests_properties(has_rbv PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;55;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_rbv_ROM "./bin/has_rbv" "--" "--rom")
set_tests_properties(has_rbv_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;55;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_scsi_io "./bin/test_scsi_io")
set_tests_properties(test_scsi_io PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;56;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_scsi_io_ROM "./bin/test_scsi_io" "--" "--rom")
set_tests_properties(test_scsi_io_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;56;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_scsi_cmd "./bin/test_scsi_cmd")
set_tests_properties(test_scsi_cmd PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;57;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_scsi_cmd_ROM "./bin/test_scsi_cmd" "--" "--rom")
set_tests_properties(test_scsi_cmd_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;57;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_iop "./bin/test_iop")
set_tests_properties(test_iop PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;58;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_iop_ROM "./bin/test_iop" "--" "--rom")
set_tests_properties(test_iop_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;58;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_ether "./bin/has_ether")
set_tests_properties(has_ether PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;59;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_ether_ROM "./bin/has_ether" "--" "--rom")
set_tests_properties(has_ether_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;59;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_lowmem1 "./bin/has_lowmem1")
set_tests_properties(has_lowmem1 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;60;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(has_lowmem1_ROM "./bin/has_lowmem1" "--" "--rom")
set_tests_properties(has_lowmem1_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;60;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(read_id_from_via "./bin/read_id_from_via")
set_tests_properties(read_id_from_via PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;61;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(read_id_from_via_ROM "./bin/read_id_from_via" "--" "--rom")
set_tests_properties(read_id_from_via_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;61;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_hw3 "./bin/init_hw3")
set_tests_properties(init_hw3 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;63;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_hw3_ROM "./bin/init_hw3" "--" "--rom")
set_tests_properties(init_hw3_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;63;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_powerbook "./bin/init_powerbook")
set_tests_properties(init_powerbook PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;64;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_powerbook_ROM "./bin/init_powerbook" "--" "--rom")
set_tests_properties(init_powerbook_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;64;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_scsi "./bin/test_scsi")
set_tests_properties(test_scsi PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;65;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_scsi_ROM "./bin/test_scsi" "--" "--rom")
set_tests_properties(test_scsi_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;65;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_flag "./bin/check_flag")
set_tests_properties(check_flag PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;66;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_flag_ROM "./bin/check_flag" "--" "--rom")
set_tests_properties(check_flag_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;66;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_model_id "./bin/test_model_id")
set_tests_properties(test_model_id PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;68;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(test_model_id_ROM "./bin/test_model_id" "--" "--rom")
set_tests_properties(test_model_id_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;68;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(get_model_id "./bin/get_model_id")
set_tests_properties(get_model_id PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;69;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(get_model_id_ROM "./bin/get_model_id" "--" "--rom")
set_tests_properties(get_model_id_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;69;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_asc2 "./bin/play_asc2")
set_tests_properties(play_asc2 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;70;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_asc2_ROM "./bin/play_asc2" "--" "--rom")
set_tests_properties(play_asc2_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;70;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_asc3 "./bin/play_asc3")
set_tests_properties(play_asc3 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;71;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_asc3_ROM "./bin/play_asc3" "--" "--rom")
set_tests_properties(play_asc3_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;71;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_asc5 "./bin/play_asc5")
set_tests_properties(play_asc5 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;72;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_asc5_ROM "./bin/play_asc5" "--" "--rom")
set_tests_properties(play_asc5_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;72;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_asc "./bin/play_asc")
set_tests_properties(play_asc PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;73;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_asc_ROM "./bin/play_asc" "--" "--rom")
set_tests_properties(play_asc_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;73;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_chime_1 "./bin/play_chime_1")
set_tests_properties(play_chime_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;74;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_chime_1_ROM "./bin/play_chime_1" "--" "--rom")
set_tests_properties(play_chime_1_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;74;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_chime_4 "./bin/play_chime_4")
set_tests_properties(play_chime_4 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;75;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_chime_4_ROM "./bin/play_chime_4" "--" "--rom")
set_tests_properties(play_chime_4_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;75;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_easc "./bin/play_easc")
set_tests_properties(play_easc PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;76;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(play_easc_ROM "./bin/play_easc" "--" "--rom")
set_tests_properties(play_easc_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;76;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(wait_until_easc_fifo_half "./bin/wait_until_easc_fifo_half")
set_tests_properties(wait_until_easc_fifo_half PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;79;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(wait_until_easc_fifo_half_ROM "./bin/wait_until_easc_fifo_half" "--" "--rom")
set_tests_properties(wait_until_easc_fifo_half_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;79;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(easc_beep "./bin/easc_beep")
set_tests_properties(easc_beep PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;80;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(easc_beep_ROM "./bin/easc_beep" "--" "--rom")
set_tests_properties(easc_beep_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;80;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(get_hw_info2 "./bin/get_hw_info2")
set_tests_properties(get_hw_info2 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;81;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(get_hw_info2_ROM "./bin/get_hw_info2" "--" "--rom")
set_tests_properties(get_hw_info2_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;81;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(send_to_pb_key "./bin/send_to_pb_key")
set_tests_properties(send_to_pb_key PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;82;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(send_to_pb_key_ROM "./bin/send_to_pb_key" "--" "--rom")
set_tests_properties(send_to_pb_key_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;82;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(send_to_pb_dword "./bin/send_to_pb_dword")
set_tests_properties(send_to_pb_dword PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;83;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(send_to_pb_dword_ROM "./bin/send_to_pb_dword" "--" "--rom")
set_tests_properties(send_to_pb_dword_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;83;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(send_to_pb_byte "./bin/send_to_pb_byte")
set_tests_properties(send_to_pb_byte PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;84;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(send_to_pb_byte_ROM "./bin/send_to_pb_byte" "--" "--rom")
set_tests_properties(send_to_pb_byte_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;84;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(recv_from_pb "./bin/recv_from_pb")
set_tests_properties(recv_from_pb PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;85;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(recv_from_pb_ROM "./bin/recv_from_pb" "--" "--rom")
set_tests_properties(recv_from_pb_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;85;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_scc_iop_fw "./bin/init_scc_iop_fw")
set_tests_properties(init_scc_iop_fw PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;86;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_scc_iop_fw_ROM "./bin/init_scc_iop_fw" "--" "--rom")
set_tests_properties(init_scc_iop_fw_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;86;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_pb_duo "./bin/init_pb_duo")
set_tests_properties(init_pb_duo PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;87;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_pb_duo_ROM "./bin/init_pb_duo" "--" "--rom")
set_tests_properties(init_pb_duo_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;87;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_easc_fifo_empty "./bin/check_easc_fifo_empty")
set_tests_properties(check_easc_fifo_empty PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;88;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_easc_fifo_empty_ROM "./bin/check_easc_fifo_empty" "--" "--rom")
set_tests_properties(check_easc_fifo_empty_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;88;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_easc_fifo_half "./bin/check_easc_fifo_half")
set_tests_properties(check_easc_fifo_half PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;89;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_easc_fifo_half_ROM "./bin/check_easc_fifo_half" "--" "--rom")
set_tests_properties(check_easc_fifo_half_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;89;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_easc_fifo_done "./bin/check_easc_fifo_done")
set_tests_properties(check_easc_fifo_done PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;90;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_easc_fifo_done_ROM "./bin/check_easc_fifo_done" "--" "--rom")
set_tests_properties(check_easc_fifo_done_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;90;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(easc_is_sonora "./bin/easc_is_sonora")
set_tests_properties(easc_is_sonora PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;91;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(easc_is_sonora_ROM "./bin/easc_is_sonora" "--" "--rom")
set_tests_properties(easc_is_sonora_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;91;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(modem_port_send1 "./bin/modem_port_send1")
set_tests_properties(modem_port_send1 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;92;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(modem_port_send1_ROM "./bin/modem_port_send1" "--" "--rom")
set_tests_properties(modem_port_send1_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;92;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(get_scc_addr "./bin/get_scc_addr")
set_tests_properties(get_scc_addr PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;93;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(get_scc_addr_ROM "./bin/get_scc_addr" "--" "--rom")
set_tests_properties(get_scc_addr_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;93;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_modem_port "./bin/init_modem_port")
set_tests_properties(init_modem_port PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;94;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_modem_port_ROM "./bin/init_modem_port" "--" "--rom")
set_tests_properties(init_modem_port_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;94;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(read_modem_port "./bin/read_modem_port")
set_tests_properties(read_modem_port PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;95;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(read_modem_port_ROM "./bin/read_modem_port" "--" "--rom")
set_tests_properties(read_modem_port_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;95;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(write_modem_port_byte "./bin/write_modem_port_byte")
set_tests_properties(write_modem_port_byte PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;96;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(write_modem_port_byte_ROM "./bin/write_modem_port_byte" "--" "--rom")
set_tests_properties(write_modem_port_byte_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;96;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(write_modem_port_cstr "./bin/write_modem_port_cstr")
set_tests_properties(write_modem_port_cstr PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;97;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(write_modem_port_cstr_ROM "./bin/write_modem_port_cstr" "--" "--rom")
set_tests_properties(write_modem_port_cstr_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;97;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(from_ascii "./bin/from_ascii")
set_tests_properties(from_ascii PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;98;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(from_ascii_ROM "./bin/from_ascii" "--" "--rom")
set_tests_properties(from_ascii_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;98;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(read_modem_cmd_dword "./bin/read_modem_cmd_dword")
set_tests_properties(read_modem_cmd_dword PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;99;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(read_modem_cmd_dword_ROM "./bin/read_modem_cmd_dword" "--" "--rom")
set_tests_properties(read_modem_cmd_dword_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;99;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(to_ascii "./bin/to_ascii")
set_tests_properties(to_ascii PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;100;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(to_ascii_ROM "./bin/to_ascii" "--" "--rom")
set_tests_properties(to_ascii_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;100;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(write_modem_integer "./bin/write_modem_integer")
set_tests_properties(write_modem_integer PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;101;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(write_modem_integer_ROM "./bin/write_modem_integer" "--" "--rom")
set_tests_properties(write_modem_integer_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;101;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(read_modem_cmd1 "./bin/read_modem_cmd1")
set_tests_properties(read_modem_cmd1 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;102;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(read_modem_cmd1_ROM "./bin/read_modem_cmd1" "--" "--rom")
set_tests_properties(read_modem_cmd1_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;102;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(comm_modem_port "./bin/comm_modem_port")
set_tests_properties(comm_modem_port PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;103;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(comm_modem_port_ROM "./bin/comm_modem_port" "--" "--rom")
set_tests_properties(comm_modem_port_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;103;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(ram_check "./bin/ram_check")
set_tests_properties(ram_check PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;104;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(ram_check_ROM "./bin/ram_check" "--" "--rom")
set_tests_properties(ram_check_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;104;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_simm "./bin/check_simm")
set_tests_properties(check_simm PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;105;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_simm_ROM "./bin/check_simm" "--" "--rom")
set_tests_properties(check_simm_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;105;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_simm_size "./bin/check_simm_size")
set_tests_properties(check_simm_size PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;106;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_simm_size_ROM "./bin/check_simm_size" "--" "--rom")
set_tests_properties(check_simm_size_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;106;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_simm_slots "./bin/check_simm_slots")
set_tests_properties(check_simm_slots PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;107;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(check_simm_slots_ROM "./bin/check_simm_slots" "--" "--rom")
set_tests_properties(check_simm_slots_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;107;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(pb_handler52 "./bin/pb_handler52")
set_tests_properties(pb_handler52 PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;109;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(pb_handler52_ROM "./bin/pb_handler52" "--" "--rom")
set_tests_properties(pb_handler52_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;109;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_adb "./bin/init_adb")
set_tests_properties(init_adb PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;20;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;110;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
add_test(init_adb_ROM "./bin/init_adb" "--" "--rom")
set_tests_properties(init_adb_ROM PROPERTIES  _BACKTRACE_TRIPLES "/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;24;add_test;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;110;UT;/home/michiaki/Document/macemu/macemu/BasiliskII/src/test/rom/CMakeLists.txt;0;")
