void op_ori_b(uint16_t  xop, int dm, int type, int  reg);
void op_ori_w(uint16_t  xop, int dm, int type, int  reg);
void op_ori_l(uint16_t  xop, int dm, int type, int  reg);
void op_andi_b(uint16_t  xop, int dm, int type, int  reg);
void op_andi_w(uint16_t  xop, int dm, int type, int  reg);
void op_andi_l(uint16_t  xop, int dm, int type, int  reg);
void op_cmp2_chk2_b(uint16_t  xop, int dm, int type, int  reg);
void op_cmp2_chk2_w(uint16_t  xop, int dm, int type, int  reg);
void op_subi_b(uint16_t  xop, int dm, int type, int  reg);
void op_subi_w(uint16_t  xop, int dm, int type, int  reg);
void op_subi_l(uint16_t  xop, int dm, int type, int  reg);
void op_cmp2_chk2_l(uint16_t  xop, int dm, int type, int  reg);
void op_addi_b(uint16_t  xop, int dm, int type, int  reg);
void op_addi_w(uint16_t  xop, int dm, int type, int  reg);
void op_addi_l(uint16_t  xop, int dm, int type, int  reg);
void op_btst_imm(uint16_t  xop, int dm, int type, int  reg);
void op_bchg_imm(uint16_t  xop, int dm, int type, int  reg);
void op_bclr_imm(uint16_t  xop, int dm, int type, int  reg);
void op_bset_imm(uint16_t  xop, int dm, int type, int  reg);
void op_eori_b(uint16_t  xop, int dm, int type, int  reg);
void op_eori_w(uint16_t  xop, int dm, int type, int  reg);
void op_eori_l(uint16_t  xop, int dm, int type, int  reg);
void op_cas_b(uint16_t  xop, int dm, int type, int  reg);
void op_cas_w(uint16_t  xop, int dm, int type, int  reg);
void op_cas_l(uint16_t  xop, int dm, int type, int  reg);
void op_cmpi_b(uint16_t  xop, int dm, int type, int  reg);
void op_cmpi_w(uint16_t  xop, int dm, int type, int  reg);
void op_cmpi_l(uint16_t  xop, int dm, int type, int  reg);
void op_moves_b(uint16_t  xop, int dm, int type, int  reg);
void op_moves_w(uint16_t  xop, int dm, int type, int  reg);
void op_moves_l(uint16_t  xop, int dm, int type, int  reg);
void op_btst_dm(uint16_t  xop, int dm, int type, int  reg);
void op_bchg_dm(uint16_t  xop, int dm, int type, int  reg);
void op_bclr_dm(uint16_t  xop, int dm, int type, int  reg);
void op_bset_dm(uint16_t  xop, int dm, int type, int  reg);
void op_move_b(uint16_t  xop, int dm, int type, int  reg);
void op_move_w(uint16_t  xop, int dm, int type, int  reg);
void op_move_l(uint16_t  xop, int dm, int type, int  reg);
void op_movea_w(uint16_t  xop, int dm, int type, int  reg);
void op_movea_l(uint16_t  xop, int dm, int type, int  reg);
void op_negx_b(uint16_t  xop, int dm, int type, int  reg);
void op_negx_w(uint16_t  xop, int dm, int type, int  reg);
void op_negx_l(uint16_t  xop, int dm, int type, int  reg);
void op_move_from_sr(uint16_t  xop, int dm, int type, int  reg);
void op_clr_b(uint16_t  xop, int dm, int type, int  reg);
void op_clr_w(uint16_t  xop, int dm, int type, int  reg);
void op_clr_l(uint16_t  xop, int dm, int type, int  reg);
void op_move_from_ccr(uint16_t  xop, int dm, int type, int  reg);
void op_neg_b(uint16_t  xop, int dm, int type, int  reg);
void op_neg_w(uint16_t  xop, int dm, int type, int  reg);
void op_neg_l(uint16_t  xop, int dm, int type, int  reg);
void op_move_to_ccr(uint16_t  xop, int dm, int type, int  reg);
void op_not_b(uint16_t  xop, int dm, int type, int  reg);
void op_not_w(uint16_t  xop, int dm, int type, int  reg);
void op_not_l(uint16_t  xop, int dm, int type, int  reg);
void op_move_to_sr(uint16_t  xop, int dm, int type, int  reg);
void op_nbcd(uint16_t  xop, int dm, int type, int  reg);
void op_0441(uint16_t  xop, int dm, int type, int  reg);
void op_movem_to_w(uint16_t  xop, int dm, int type, int  reg);
void op_movem_to_l(uint16_t  xop, int dm, int type, int  reg);
void op_tst_b(uint16_t  xop, int dm, int type, int  reg);
void op_tst_w(uint16_t  xop, int dm, int type, int  reg);
void op_tst_l(uint16_t  xop, int dm, int type, int  reg);
void op_tas(uint16_t  xop, int dm, int type, int  reg);
void op_mul_l(uint16_t  xop, int dm, int type, int  reg);
void op_div_l(uint16_t  xop, int dm, int type, int  reg);
void op_movem_from_w(uint16_t  xop, int dm, int type, int  reg);
void op_movem_from_l(uint16_t  xop, int dm, int type, int  reg);
void op_0471(uint16_t  xop, int dm, int type, int  reg);

void op_jsr(uint16_t  xop, int dm, int type, int  reg);
void op_jmp(uint16_t  xop, int dm, int type, int  reg);
void op_chk_w(uint16_t  xop, int dm, int type, int  reg);
void op_chk_l(uint16_t  xop, int dm, int type, int  reg);
void op_lea(uint16_t  xop, int dm, int type, int  reg);
void op_addq_b(uint16_t  xop, int dm, int type, int  reg);
void op_addq_w(uint16_t  xop, int dm, int type, int  reg);
void op_addq_l(uint16_t  xop, int dm, int type, int  reg);
void op_subq_b(uint16_t  xop, int dm, int type, int  reg);
void op_subq_w(uint16_t  xop, int dm, int type, int  reg);
void op_subq_l(uint16_t  xop, int dm, int type, int  reg);
void op_scc(uint16_t  xop, int dm, int type, int  reg);

void op_bra(uint16_t  xop, int dm, int type, int  reg);
void op_bsr(uint16_t  xop, int dm, int type, int  reg);
void op_bcc(uint16_t  xop, int dm, int type, int  reg);
void op_moveq(uint16_t  xop, int dm, int type, int  reg);
void op_or_b(uint16_t  xop, int dm, int type, int  reg);
void op_or_w(uint16_t  xop, int dm, int type, int  reg);
void op_or_l(uint16_t  xop, int dm, int type, int  reg);
void op_or_to_ea_b(uint16_t  xop, int dm, int type, int  reg);
void op_or_to_ea_w(uint16_t  xop, int dm, int type, int  reg);
void op_or_to_ea_l(uint16_t  xop, int dm, int type, int  reg);
void op_divu_w(uint16_t  xop, int dm, int type, int  reg);
void op_divs_w(uint16_t  xop, int dm, int type, int  reg);
void op_sub_b(uint16_t  xop, int dm, int type, int  reg);
void op_sub_w(uint16_t  xop, int dm, int type, int  reg);
void op_sub_l(uint16_t  xop, int dm, int type, int  reg);
void op_suba_w(uint16_t  xop, int dm, int type, int  reg);
void op_suba_l(uint16_t  xop, int dm, int type, int  reg);
void op_sub_to_ea_b(uint16_t  xop, int dm, int type, int  reg);
void op_sub_to_ea_w(uint16_t  xop, int dm, int type, int  reg);
void op_sub_to_ea_l(uint16_t  xop, int dm, int type, int  reg);
void op_cmp_b(uint16_t  xop, int dm, int type, int  reg);
void op_cmp_w(uint16_t  xop, int dm, int type, int  reg);
void op_cmp_l(uint16_t  xop, int dm, int type, int  reg);
void op_cmpa_w(uint16_t  xop, int dm, int type, int  reg);
void op_eor_b(uint16_t  xop, int dm, int type, int  reg);
void op_eor_w(uint16_t  xop, int dm, int type, int  reg);
void op_eor_l(uint16_t  xop, int dm, int type, int  reg);
void op_cmpa_l(uint16_t  xop, int dm, int type, int  reg);

void op_and_b(uint16_t  xop, int dm, int type, int  reg);
void op_and_w(uint16_t  xop, int dm, int type, int  reg);
void op_and_l(uint16_t  xop, int dm, int type, int  reg);
void op_mulu_w(uint16_t  xop, int dm, int type, int  reg);
void op_and_to_ea_b(uint16_t  xop, int dm, int type, int  reg);
void op_and_to_ea_w(uint16_t  xop, int dm, int type, int  reg);
void op_and_to_ea_l(uint16_t  xop, int dm, int type, int  reg);
void op_muls_w(uint16_t  xop, int dm, int type, int  reg);
void op_add_b(uint16_t  xop, int dm, int type, int  reg);
void op_add_w(uint16_t  xop, int dm, int type, int  reg);
void op_add_l(uint16_t  xop, int dm, int type, int  reg);
void op_adda_w(uint16_t  xop, int dm, int type, int  reg);
void op_adda_l(uint16_t  xop, int dm, int type, int  reg);
void op_add_to_ea_b(uint16_t  xop, int dm, int type, int  reg);
void op_add_to_ea_w(uint16_t  xop, int dm, int type, int  reg);
void op_add_to_ea_l(uint16_t  xop, int dm, int type, int  reg);
void op_shr_b(uint16_t  xop, int dm, int type, int  reg);
void op_shr_w(uint16_t  xop, int dm, int type, int  reg);
void op_shr_l(uint16_t  xop, int dm, int type, int  reg);
void op_asr_ea(uint16_t  xop, int dm, int type, int  reg);
void op_lsr_ea(uint16_t  xop, int dm, int type, int  reg);
void op_roxr_ea(uint16_t  xop, int dm, int type, int  reg);
void op_ror_ea(uint16_t  xop, int dm, int type, int  reg);

void op_bftst(uint16_t  xop, int dm, int type, int  reg);
void op_bfchg(uint16_t  xop, int dm, int type, int  reg);
void op_bfclr(uint16_t  xop, int dm, int type, int  reg);
void op_bfset(uint16_t  xop, int dm, int type, int  reg);

void op_shl_b(uint16_t  xop, int dm, int type, int  reg);
void op_shl_w(uint16_t  xop, int dm, int type, int  reg);
void op_shl_l(uint16_t  xop, int dm, int type, int  reg);

void op_asl_ea(uint16_t  xop, int dm, int type, int  reg);
void op_lsl_ea(uint16_t  xop, int dm, int type, int  reg);
void op_roxl_ea(uint16_t  xop, int dm, int type, int  reg);
void op_rol_ea(uint16_t  xop, int dm, int type, int  reg);
void op_bfextu(uint16_t  xop, int dm, int type, int  reg);
void op_bfexts(uint16_t  xop, int dm, int type, int  reg);
void op_bfffo(uint16_t  xop, int dm, int type, int  reg);
void op_bfins(uint16_t  xop, int dm, int type, int  reg);

void op_move16(uint16_t  xop, int dm, int type, int  reg);

void op_movep_w_from(int dm, int reg);
void op_movep_l_from(int dm, int reg);
void op_movep_w_to(int dm, int reg);
void op_movep_l_to(int dm, int reg);
void op_link_l(int reg);

void op_swap(int reg);
void op_bkpt();
void op_pea(int type, int reg);

void op_ext_w(int reg);
void op_ext_l(int reg);

void op_trap(int vec);
void op_link_w(int reg);
void op_unlk(int reg);
void op_move_to_usp(int reg);
void op_move_from_usp(int reg);
void op_reset();
void op_nop();
void op_stop();
void op_rte();
void op_rtd();
void op_rts();
void op_trapv();
void op_rtr();
void op_movec_from();
void op_movec_to();

void op_extb(int reg) ;

void op_sbcd_d(int dm, int reg);
void op_sbcd_a(int dm, int reg);
void op_pack_d(int dm, int reg);
void op_pack_a(int dm, int reg);
void op_unpk_d(int dm, int reg);
void op_unpk_a(int dm, int reg);

void op_cmpm_b(int y, int x);
void op_cmpm_w(int y, int x);
void op_cmpm_l(int y, int x);

void op_abcd_d(int dm, int reg);
void op_abcd_a(int dm, int reg);

void op_exg_d(int dm, int reg);
void op_exg_a(int dm, int reg);
void op_exg_da(int dm, int reg);
